image: Visual Studio 2017
version: '{build}'
max_jobs: 4
clone_depth: 5
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
only_commits:
  files:
    - SickChill.iss
    - idp/**
    - assets/**
    - appveyor.yml

install:
  - ps: choco install -y --no-progress InnoSetup

before_build:
  - ps: |-
        $InstallerVersion = Select-String -Path .\SickChill.iss `
        -Pattern '^#define\sInstallerVersion\s([\d]+)' | `
        % { $($_.matches.groups[1]).Value };
        
        $SeedVersion = Select-String -Path .\seed.ini `
        -Pattern '^Version=([\d]+)' | `
        % { $($_.matches.groups[1]).Value };
        
        If ($InstallerVersion -ne $SeedVersion `
        -and $APPVEYOR_REPO_BRANCH -ne "master" `
        -and -not $APPVEYOR_PULL_REQUEST_NUMBER) { `
          "`nSeed version differs from version in source code!" + `
          "`n  Version in source code: $InstallerVersion" + `
          "`n  Version in seed file:   $SeedVersion" + `
          "`nMake sure to update the value before pushing to master." `
          | Write-Warning }

build_script:
  - cmd: iscc.exe /Q SickChill.iss

test: off

artifacts:
  - path: Output\windows-sickchill.exe
    name: windows-sickchill.exe

before_deploy:
  - ps: |-
        $env:ReleaseVersion = Select-String -Path .\SickChill.iss `
        -Pattern '^#define\swindows-sickchill\s"(v[\d.]+)"' | `
        % { $($_.matches.groups[1]).Value };
        If ($InstallerVersion -ne $SeedVersion) { `
          throw "Seed version differs from version in source code!`n" + `
                "`tVersion in source code: $InstallerVersion`n" + `
                "`tVersion in seed file:   $SeedVersion" + `
                "You have to update the value before releasing" }

deploy:
  - provider: GitHub
    tag: $(ReleaseVersion)
    force_update: true         # replaces current release
    draft: true                # release as a draft
    auth_token:
      secure: gsxaw2HAH3MKoCppwwPy6LBmfbcDMbbTyTRZza+tc1Hda+Qr7MhswHhp6wqJoZQj
    artifact: windows-sickchill.exe
    on:
      branch: master           # release from master branch only
